#!/usr/bin/env python3
# Phase 1b of ADR-045: base routine inventory.
# Inventory only — no role, no globals-touched, no call graph. Phase 2+.
# Spec: docs/vista-meta-spec-v0.4.md § 11

"""Build host-side routine inventory from the vista-m-host snapshot.

Reads vista/vista-m-host/MANIFEST.tsv (generated by the Docker build, copied
to host by `make sync-routines`) and stats each routine to emit:
  - vista/export/code-model/routines.tsv  (one row per routine)
  - vista/export/code-model/packages.tsv  (one row per package)
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
HOST_SNAPSHOT = PROJECT_ROOT / "vista/vista-m-host"
MANIFEST = HOST_SNAPSHOT / "MANIFEST.tsv"
OUT_DIR = PROJECT_ROOT / "vista/export/code-model"
ROUTINES_TSV = OUT_DIR / "routines.tsv"
PACKAGES_TSV = OUT_DIR / "packages.tsv"

# MANIFEST rows carry the container path; translate to the host snapshot.
CONTAINER_PREFIX = "/opt/VistA-M/"
HOST_PREFIX = str(HOST_SNAPSHOT) + "/"

ROUTINE_FIELDS = [
    "routine_name",
    "package",
    "source_path",
    "line_count",
    "byte_size",
    "first_line_comment",
    "version_line",
    "tag_count",
    "comment_line_count",
    "is_percent_routine",
]
PACKAGE_FIELDS = [
    "package",
    "routine_count",
    "percent_routine_count",
    "total_lines",
    "total_bytes",
]

# MUMPS label: line starts in column 0 with an alphanumeric char or '%'.
# Everything else (whitespace, ';', blank) is not a label line.
_LABEL_CHARS = set(b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%")


def translate(container_path: str) -> Path:
    if not container_path.startswith(CONTAINER_PREFIX):
        raise ValueError(f"Unexpected source path in MANIFEST: {container_path}")
    return Path(HOST_PREFIX + container_path[len(CONTAINER_PREFIX):])


def truncate(s: str, n: int = 120) -> str:
    return s if len(s) <= n else s[: n - 3] + "..."


def scan_routine(host_path: Path) -> dict:
    data = host_path.read_bytes()
    byte_size = len(data)
    line_count = data.count(b"\n")
    if data and not data.endswith(b"\n"):
        line_count += 1

    lines = data.split(b"\n")
    # Drop a trailing empty element caused by a final newline.
    if lines and lines[-1] == b"":
        lines = lines[:-1]

    first_line = lines[0] if lines else b""
    first_line_comment = truncate(
        first_line.decode("utf-8", errors="replace").strip()
    )

    # VistA convention: line 2 is typically ` ;;VERSION;PACKAGE;SEQ;BUILDDATE`.
    # Body lines are space-indented, so `;;` is at col 1, not col 0.
    version_line = ""
    if len(lines) >= 2 and lines[1].lstrip().startswith(b";;"):
        version_line = truncate(lines[1].decode("utf-8", errors="replace").strip())

    tag_count = 0
    comment_line_count = 0
    for ln in lines:
        if not ln:
            continue
        if ln[0:1] in (b" ", b"\t"):
            # Body line; may still be a comment-only body.
            if ln.lstrip().startswith(b";"):
                comment_line_count += 1
            continue
        if ln[0:1] == b";":
            # Line starting with ';' in column 0 (rare but valid comment form).
            comment_line_count += 1
            continue
        if ln[0] in _LABEL_CHARS:
            tag_count += 1

    return {
        "line_count": line_count,
        "byte_size": byte_size,
        "first_line_comment": first_line_comment,
        "version_line": version_line,
        "tag_count": tag_count,
        "comment_line_count": comment_line_count,
    }


def main() -> int:
    if not MANIFEST.exists():
        print(
            f"ERROR: {MANIFEST} not found. Run `make sync-routines` first.",
            file=sys.stderr,
        )
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    seen: dict[str, str] = {}
    missing: list[str] = []
    manifest_rows = 0

    with MANIFEST.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for entry in reader:
            manifest_rows += 1
            name, pkg, src = entry["routine"], entry["package"], entry["source"]

            if name in seen and seen[name] != pkg:
                print(
                    f"ERROR: routine {name} appears in two packages: "
                    f"{seen[name]!r} and {pkg!r}",
                    file=sys.stderr,
                )
                return 1
            seen[name] = pkg

            host_path = translate(src)
            if not host_path.exists():
                missing.append(str(host_path))
                continue

            features = scan_routine(host_path)
            rows.append({
                "routine_name": name,
                "package": pkg,
                "source_path": src,
                "is_percent_routine": "Y" if name.startswith("_") else "N",
                **features,
            })

    if missing:
        print(
            f"ERROR: {len(missing)} MANIFEST entries missing from host snapshot:",
            file=sys.stderr,
        )
        for p in missing[:10]:
            print(f"  {p}", file=sys.stderr)
        if len(missing) > 10:
            print(f"  ... and {len(missing) - 10} more", file=sys.stderr)
        return 1

    if len(rows) != manifest_rows:
        print(
            f"ERROR: row count mismatch: scanned {len(rows)} vs "
            f"MANIFEST {manifest_rows}",
            file=sys.stderr,
        )
        return 1

    rows.sort(key=lambda r: r["routine_name"])
    with ROUTINES_TSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=ROUTINE_FIELDS, delimiter="\t")
        w.writeheader()
        w.writerows(rows)

    pkg_stats: dict[str, dict] = defaultdict(
        lambda: {
            "routine_count": 0,
            "percent_routine_count": 0,
            "total_lines": 0,
            "total_bytes": 0,
        }
    )
    for r in rows:
        s = pkg_stats[r["package"]]
        s["routine_count"] += 1
        if r["is_percent_routine"] == "Y":
            s["percent_routine_count"] += 1
        s["total_lines"] += r["line_count"]
        s["total_bytes"] += r["byte_size"]

    pkg_rows = [{"package": n, **s} for n, s in sorted(pkg_stats.items())]
    with PACKAGES_TSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=PACKAGE_FIELDS, delimiter="\t")
        w.writeheader()
        w.writerows(pkg_rows)

    total_lines = sum(r["line_count"] for r in rows)
    total_bytes = sum(r["byte_size"] for r in rows)
    print(f"routines.tsv:  {len(rows):,} rows")
    print(f"packages.tsv:  {len(pkg_rows):,} rows")
    print(f"total lines:   {total_lines:,}")
    print(f"total bytes:   {total_bytes:,}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
