#!/usr/bin/env python3
# Phase 1b of ADR-045: base routine inventory.
# Inventory only — no role, no globals-touched, no call graph. Phase 2+.
# Spec: docs/vista-meta-spec-v0.4.md § 11

"""Build host-side routine inventory from the vista-m-host snapshot.

Reads vista/vista-m-host/MANIFEST.tsv (generated by the Docker build, copied
to host by `make sync-routines`) and stats each routine to emit:
  - vista/export/normalized/routines.tsv  (one row per routine)
  - vista/export/normalized/packages.tsv  (one row per package)
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]
HOST_SNAPSHOT = PROJECT_ROOT / "vista/vista-m-host"
MANIFEST = HOST_SNAPSHOT / "MANIFEST.tsv"
OUT_DIR = PROJECT_ROOT / "vista/export/normalized"
ROUTINES_TSV = OUT_DIR / "routines.tsv"
PACKAGES_TSV = OUT_DIR / "packages.tsv"

# MANIFEST rows carry the container path; translate to the host snapshot.
CONTAINER_PREFIX = "/opt/VistA-M/"
HOST_PREFIX = str(HOST_SNAPSHOT) + "/"

ROUTINE_FIELDS = [
    "routine_name",
    "package",
    "source_path",
    "line_count",
    "byte_size",
    "first_line_comment",
]
PACKAGE_FIELDS = ["package", "routine_count", "total_lines", "total_bytes"]


def translate(container_path: str) -> Path:
    if not container_path.startswith(CONTAINER_PREFIX):
        raise ValueError(f"Unexpected source path in MANIFEST: {container_path}")
    return Path(HOST_PREFIX + container_path[len(CONTAINER_PREFIX):])


def scan_routine(host_path: Path) -> tuple[int, int, str]:
    data = host_path.read_bytes()
    byte_size = len(data)
    line_count = data.count(b"\n")
    if data and not data.endswith(b"\n"):
        line_count += 1
    nl = data.find(b"\n")
    first = (data if nl == -1 else data[:nl]).decode("utf-8", errors="replace").strip()
    if len(first) > 120:
        first = first[:117] + "..."
    return line_count, byte_size, first


def main() -> int:
    if not MANIFEST.exists():
        print(
            f"ERROR: {MANIFEST} not found. Run `make sync-routines` first.",
            file=sys.stderr,
        )
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    seen: dict[str, str] = {}
    missing: list[str] = []
    manifest_rows = 0

    with MANIFEST.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for entry in reader:
            manifest_rows += 1
            name, pkg, src = entry["routine"], entry["package"], entry["source"]

            if name in seen and seen[name] != pkg:
                print(
                    f"ERROR: routine {name} appears in two packages: "
                    f"{seen[name]!r} and {pkg!r}",
                    file=sys.stderr,
                )
                return 1
            seen[name] = pkg

            host_path = translate(src)
            if not host_path.exists():
                missing.append(str(host_path))
                continue

            lines, size, comment = scan_routine(host_path)
            rows.append({
                "routine_name": name,
                "package": pkg,
                "source_path": src,
                "line_count": lines,
                "byte_size": size,
                "first_line_comment": comment,
            })

    if missing:
        print(
            f"ERROR: {len(missing)} MANIFEST entries missing from host snapshot:",
            file=sys.stderr,
        )
        for p in missing[:10]:
            print(f"  {p}", file=sys.stderr)
        if len(missing) > 10:
            print(f"  ... and {len(missing) - 10} more", file=sys.stderr)
        return 1

    if len(rows) != manifest_rows:
        print(
            f"ERROR: row count mismatch: scanned {len(rows)} vs "
            f"MANIFEST {manifest_rows}",
            file=sys.stderr,
        )
        return 1

    rows.sort(key=lambda r: r["routine_name"])
    with ROUTINES_TSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=ROUTINE_FIELDS, delimiter="\t")
        w.writeheader()
        w.writerows(rows)

    pkg_stats: dict[str, dict] = defaultdict(
        lambda: {"routine_count": 0, "total_lines": 0, "total_bytes": 0}
    )
    for r in rows:
        s = pkg_stats[r["package"]]
        s["routine_count"] += 1
        s["total_lines"] += r["line_count"]
        s["total_bytes"] += r["byte_size"]

    pkg_rows = [{"package": n, **s} for n, s in sorted(pkg_stats.items())]
    with PACKAGES_TSV.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=PACKAGE_FIELDS, delimiter="\t")
        w.writeheader()
        w.writerows(pkg_rows)

    total_lines = sum(r["line_count"] for r in rows)
    total_bytes = sum(r["byte_size"] for r in rows)
    print(f"routines.tsv:  {len(rows):,} rows")
    print(f"packages.tsv:  {len(pkg_rows):,} rows")
    print(f"total lines:   {total_lines:,}")
    print(f"total bytes:   {total_bytes:,}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
