#!/usr/bin/env python3
# Phase 1b of ADR-045: base routine inventory.
# Inventory only — no role, no globals-touched, no call graph. Phase 2+.
# Spec: docs/reference/model-extraction-contract.md § 11

"""Build host-side routine inventory from the vista-m-host snapshot.

Reads vista/vista-m-host/MANIFEST.tsv (generated by the Docker build, copied
to host by `make sync-routines`) and stats each routine to emit:
  - vista/export/code-model/routines.tsv  (one row per routine)
  - vista/export/code-model/packages.tsv  (one row per package)
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

import schema_v1
import tsvio

PROJECT_ROOT = Path(__file__).resolve().parents[2]
HOST_SNAPSHOT = PROJECT_ROOT / "vista/vista-m-host"
MANIFEST = HOST_SNAPSHOT / "MANIFEST.tsv"
# R4: %-routines synced from the image's VistA dirs (ZTMGRSET set in
# /opt/VistA-M/o plus /opt/VistA-M/r strays) — NEVER from $ydb_dist,
# whose _*.m are YottaDB's own utilities, not VistA. The census
# boundary is membership in this mini-manifest.
PERCENT_DIR = HOST_SNAPSHOT / "PercentRoutines"
PERCENT_MANIFEST = PERCENT_DIR / "MANIFEST.tsv"
PACKAGES_CSV = PROJECT_ROOT / "docs/Packages.csv"
OUT_DIR = PROJECT_ROOT / "vista/export/code-model"
ROUTINES_TSV = OUT_DIR / "routines.tsv"
PACKAGES_TSV = OUT_DIR / "packages.tsv"

# MANIFEST rows carry the container path; translate to the host snapshot.
CONTAINER_PREFIX = "/opt/VistA-M/"
HOST_PREFIX = str(HOST_SNAPSHOT) + "/"

ROUTINES_SPEC = schema_v1.spec_for("routines.tsv")
PACKAGES_SPEC = schema_v1.spec_for("packages.tsv")

# MUMPS label: line starts in column 0 with an alphanumeric char or '%'.
# Everything else (whitespace, ';', blank) is not a label line.
_LABEL_CHARS = set(b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789%")


def translate(container_path: str) -> Path:
    if not container_path.startswith(CONTAINER_PREFIX):
        raise ValueError(f"Unexpected source path in MANIFEST: {container_path}")
    return Path(HOST_PREFIX + container_path[len(CONTAINER_PREFIX):])


def truncate(s: str, n: int = 120) -> str:
    return s if len(s) <= n else s[: n - 3] + "..."


def scan_routine(host_path: Path) -> dict:
    data = host_path.read_bytes()
    byte_size = len(data)
    line_count = data.count(b"\n")
    if data and not data.endswith(b"\n"):
        line_count += 1

    lines = data.split(b"\n")
    # Drop a trailing empty element caused by a final newline.
    if lines and lines[-1] == b"":
        lines = lines[:-1]

    first_line = lines[0] if lines else b""
    first_line_comment = truncate(
        first_line.decode("utf-8", errors="replace").strip()
    )

    # VistA convention: line 2 is typically ` ;;VERSION;PACKAGE;SEQ;BUILDDATE`.
    # Body lines are space-indented, so `;;` is at col 1, not col 0.
    version_line = ""
    if len(lines) >= 2 and lines[1].lstrip().startswith(b";;"):
        version_line = truncate(lines[1].decode("utf-8", errors="replace").strip())

    tag_count = 0
    comment_line_count = 0
    for ln in lines:
        if not ln:
            continue
        if ln[0:1] in (b" ", b"\t"):
            # Body line; may still be a comment-only body.
            if ln.lstrip().startswith(b";"):
                comment_line_count += 1
            continue
        if ln[0:1] == b";":
            # Line starting with ';' in column 0 (rare but valid comment form).
            comment_line_count += 1
            continue
        if ln[0] in _LABEL_CHARS:
            tag_count += 1

    return {
        "line_count": line_count,
        "byte_size": byte_size,
        "first_line_comment": first_line_comment,
        "version_line": version_line,
        "tag_count": tag_count,
        "comment_line_count": comment_line_count,
    }


def version_line_package(version_line: str) -> str:
    """Extract the package name from a VistA version line.

    Convention: ` ;;<version>;<PACKAGE NAME>;<patches>;<date>` — the
    package is the 2nd `;;`-payload field. Returns "" when absent.
    """
    s = version_line.strip()
    if not s.startswith(";;"):
        return ""
    parts = s.split(";")
    # parts: ['', '', '<version>', '<package>', ...]
    return parts[3].strip() if len(parts) > 3 else ""


def percent_rows(percent_dir: Path, name_to_dir: dict[str, str]) -> list[dict]:
    """Census rows for the %-routines listed in the mini-manifest.

    Package attribution: the routine's own version line names its VA
    package (e.g. `;;22.2;VA FileMan;…`), mapped case-insensitively
    through docs/Packages.csv to the canonical directory name.
    Non-VA packages (e.g. YottaDB's Octo mapper) stay blank (null).
    """
    manifest = percent_dir / "MANIFEST.tsv"
    rows: list[dict] = []
    with manifest.open(newline="", encoding="utf-8") as fh:
        for entry in csv.DictReader(fh, delimiter="\t"):
            name, src = entry["routine"], entry["source"]
            host_path = percent_dir / Path(src).name
            features = scan_routine(host_path)
            pkg = name_to_dir.get(
                version_line_package(features["version_line"]).upper(), "")
            rows.append({
                "routine_name": name,
                "package": pkg,
                "source_path": src,
                "is_percent_routine": "Y",
                **features,
            })
    return rows


def main() -> int:
    if not MANIFEST.exists():
        print(
            f"ERROR: {MANIFEST} not found. Run `make sync-routines` first.",
            file=sys.stderr,
        )
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    seen: dict[str, str] = {}
    missing: list[str] = []
    manifest_rows = 0

    with MANIFEST.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh, delimiter="\t")
        for entry in reader:
            manifest_rows += 1
            name, pkg, src = entry["routine"], entry["package"], entry["source"]

            if name in seen and seen[name] != pkg:
                print(
                    f"ERROR: routine {name} appears in two packages: "
                    f"{seen[name]!r} and {pkg!r}",
                    file=sys.stderr,
                )
                return 1
            seen[name] = pkg

            host_path = translate(src)
            if not host_path.exists():
                missing.append(str(host_path))
                continue

            features = scan_routine(host_path)
            rows.append({
                "routine_name": name,
                "package": pkg,
                "source_path": src,
                "is_percent_routine": "Y" if name.startswith("_") else "N",
                **features,
            })

    if missing:
        print(
            f"ERROR: {len(missing)} MANIFEST entries missing from host snapshot:",
            file=sys.stderr,
        )
        for p in missing[:10]:
            print(f"  {p}", file=sys.stderr)
        if len(missing) > 10:
            print(f"  ... and {len(missing) - 10} more", file=sys.stderr)
        return 1

    if len(rows) != manifest_rows:
        print(
            f"ERROR: row count mismatch: scanned {len(rows)} vs "
            f"MANIFEST {manifest_rows}",
            file=sys.stderr,
        )
        return 1

    # R4: the %-namespace census. Required — a census without it is
    # the measured pre-v1 defect (39,330 routines, zero %-routines).
    if not PERCENT_MANIFEST.exists():
        print(
            f"ERROR: {PERCENT_MANIFEST} not found. "
            "Run `make sync-routines` first (R4 %-routine census).",
            file=sys.stderr,
        )
        return 1
    from build_package_namespace import parse_packages_csv  # local import
    name_to_dir = {
        e.get("package_name", "").upper(): d
        for d, e in parse_packages_csv(PACKAGES_CSV).items()
        if e.get("package_name")
    }
    pct = percent_rows(PERCENT_DIR, name_to_dir)
    dup = {r["routine_name"] for r in pct} & set(seen)
    if dup:
        print(f"ERROR: %-routines collide with census: {sorted(dup)}",
              file=sys.stderr)
        return 1
    rows.extend(pct)

    tsvio.write_spec(ROUTINES_TSV, ROUTINES_SPEC, rows)

    pkg_stats: dict[str, dict] = defaultdict(
        lambda: {
            "routine_count": 0,
            "percent_routine_count": 0,
            "total_lines": 0,
            "total_bytes": 0,
        }
    )
    for r in rows:
        if not r["package"]:
            # Unattributed %-routines (non-VA, e.g. YDBOcto) stay out
            # of the per-package aggregate; packages.tsv PK is package.
            continue
        s = pkg_stats[r["package"]]
        s["routine_count"] += 1
        if r["is_percent_routine"] == "Y":
            s["percent_routine_count"] += 1
        s["total_lines"] += r["line_count"]
        s["total_bytes"] += r["byte_size"]

    pkg_rows = [{"package": n, **s} for n, s in pkg_stats.items()]
    tsvio.write_spec(PACKAGES_TSV, PACKAGES_SPEC, pkg_rows)

    total_lines = sum(r["line_count"] for r in rows)
    total_bytes = sum(r["byte_size"] for r in rows)
    print(f"routines.tsv:  {len(rows):,} rows")
    print(f"packages.tsv:  {len(pkg_rows):,} rows")
    print(f"total lines:   {total_lines:,}")
    print(f"total bytes:   {total_bytes:,}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
